First version of function
fed-team/js-test pull request #1
Opened 2019-06-29 18:08 UTC by hendrysiak

2019-06-29 18:33 UTC, mras2303 commented on users.js
> +const newUserArr = [];
1. Skoro widzę, że to tablica, to nie nazywaj jej jeszcze dodatkowo `Arr`.
2. Nazwa newUsers byłaby lepsza, liczba mnoga, ze względu na to, że trzymamy w zmiennej kolekcję.

2019-06-29 18:35 UTC, mras2303 commented on users.js
> +function handleUsersData() {
Zmieniłbym to na deklarację funkcji za pomocą const

function handleUsersData() {

=>

`const handleUsersData = users => { ... }`

2019-06-29 18:36 UTC, mras2303 commented on users.js
> +      .replace(/\./gi, "/")
Zmieniasz kropki na slashe, a potem po nich rozdzielasz stringa, czym różni się to od 

`const dateParser = user.lastly.slice(6).split(".")`

?

2019-06-29 18:40 UTC, mras2303 commented on users.js
> +      if (timeFromPost > 30) {
Linie 71-75

Możesz to zapisać w jednej linii

`user.online = timeFromPost <= 30;`
lub
`user.online = !timeFromPost > 30;`

2019-06-29 20:29 UTC, hayuna requested changes

2019-06-29 20:29 UTC, mras2303 commented on users.js
> +    const dateParser = user.lastly.slice(6).split("/");
Format daty w polu lastly rozdzielony jest kropką, nie slashem

2019-06-29 21:06 UTC, hayuna approved these changes

2019-06-29 21:29 UTC, mras2303 commented
Klient sobie zażyczył, żeby backendowcy zmienili datę w polu lately na 
`today at 23:00`
`yesterday at 10:05`

w przypadku gdy wpis nastąpi w dzień pobrania danych z API lub w przeddzień.

Czy mógłbyś zmodyfikować kod, aby spełniał te warunki?

2019-06-30 08:29 UTC, hendrysiak commented
> Klient sobie zażyczył, żeby backendowcy zmienili datę w polu lately na
> `today at 23:00`
> `yesterday at 10:05`
> 
> w przypadku gdy wpis nastąpi w dzień pobrania danych z API lub w przeddzień.
> 
> Czy mógłbyś zmodyfikować kod, aby spełniał te warunki?

Mam napisać osobny mikroserwis backendowy, który wysyła dane po pobraniu daty i weryfikacji oraz połączyć z obecnym zestawem, czy tylko wprowadzić obsługę po stronie frontu?

2019-06-30 08:53 UTC, mras2303 commented
> > Klient sobie zażyczył, żeby backendowcy zmienili datę w polu lately na
> > `today at 23:00`
> > `yesterday at 10:05`
> > w przypadku gdy wpis nastąpi w dzień pobrania danych z API lub w przeddzień.
> > Czy mógłbyś zmodyfikować kod, aby spełniał te warunki?
> 
> Mam napisać osobny mikroserwis backendowy, który wysyła dane po pobraniu daty i weryfikacji oraz połączyć z obecnym zestawem, czy tylko wprowadzić obsługę po stronie frontu?

Tylko obsługa w obecnym kodzie

2019-06-30 09:22 UTC, mras2303 commented
Dodałem jednego usera do bazy danych

`{ id: 46, name: "Marek Kowalonek", lastly: "today at 11:10" }`

obecny wynik:

> [ ...
>   { id: 39, name: 'Willis Ross', lastly: 'yesterday at 01:13 06.01.2017', online: false },
>   { id: 40, name: 'Mavis James', lastly: 'yesterday at 22:13 03.10.2015', online: false },
>   { id: 41, name: 'Lana Clay', lastly: 'yesterday at 01:00 01.01.1970', online: false },
>   { id: 43, name: 'Helga Glenn', lastly: 'yesterday at 01:00 01.01.1970', online: false },
>   { id: 44, name: 'Mays Noel', lastly: 'yesterday at 00:00 18.04.2017', online: false },
>   { id: 45, name: 'Marek Kowalonek', lastly: 'yesterday at today at 11:10', online: false } 
> ]

oczekiwany wynik:
> [ ...
>   { id: ..., name: 'Willis Ross', lastly: '01:13 06.01.2017', online: false },
>   { id: ..., name: 'Mavis James', lastly: '22:13 03.10.2015', online: false },
>   { id: ..., name: 'Lana Clay', lastly: '01:00 01.01.1970', online: false },
>   { id: ..., name: 'Helga Glenn', lastly: '01:00 01.01.1970', online: false },
>   { id: ..., name: 'Mays Noel', lastly: '00:00 18.04.2017', online: false },
>   { id: ..., name: 'Marek Kowalonek', lastly: 'today at 11:10', online: true } 
> ]

2019-06-30 19:35 UTC, hendrysiak commented
> > > Klient sobie zażyczył, żeby backendowcy zmienili datę w polu lately na
> > > `today at 23:00`
> > > `yesterday at 10:05`
> > > w przypadku gdy wpis nastąpi w dzień pobrania danych z API lub w przeddzień.
> > > Czy mógłbyś zmodyfikować kod, aby spełniał te warunki?
> > 
> > 
> > Mam napisać osobny mikroserwis backendowy, który wysyła dane po pobraniu daty i weryfikacji oraz połączyć z obecnym zestawem, czy tylko wprowadzić obsługę po stronie frontu?
> 
> Tylko obsługa w obecnym kodzie

Trochę się zakręciłem i nie zrozumiałem koncepcji :) teraz powinno działać, aczkolwiek krytyka mile widziana!

2019-06-30 20:12 UTC, mras2303 commented
Nadal problemy z today/yesterday

>Input
`const users = [
	{"id":786,"name":"Reilly Beach","lastly":"19:29 29.07.2018"},
  	{"id":1023,"name":"Duncan Contreras","lastly":"20:46 03.04.2014"},
  	{"id":1980,"name":"Eddie Potts","lastly":"14:39 30.09.2013"},
  	{"id":3529,"name":"Jeannette Evans","lastly":"06:45 29.09.2018"},
  	{"id":3851,"name":"Effie Knowles","lastly":"19:25 29.07.2018"}
  ]`
>Actual
`
[
{"id":785,"name":"Reilly Beach","lastly":"yesterday at 19:29 29.07.2018","online":false},
{"id":1022,"name":"Duncan Contreras","lastly":"Yesterday at 21:58","online":false},
{"id":1979,"name":"Eddie Potts","lastly":"today at 14:39 30.09.2013","online":false},
{"id":3528,"name":"Jeannette Evans","lastly":"yesterday at 06:45 29.09.2018","online":false},
{"id":3850,"name":"Effie Knowles","lastly":"yesterday at 19:25 29.07.2018","online":false}
]
`
> Expected
`
[
{"id":785,"name":"Reilly Beach","lastly":"19:29 29.07.2018","online":false},
{"id":1022,"name":"Duncan Contreras","lastly":"Yesterday at 21:58","online":true},
{"id":1979,"name":"Eddie Potts","lastly":"14:39 30.09.2013","online":false},
{"id":3528,"name":"Jeannette Evans","lastly":"06:45 29.09.2018","online":false},
{"id":3850,"name":"Effie Knowles","lastly":"19:25 29.07.2018","online":false}
]
`

2019-06-30 20:27 UTC, hendrysiak commented
Chyba mam gorszy dzień i miałem poczekać do dnia roboczego z tym :/ pewnie teraz działa, ale sam nie wierzę w to, jak dałem dupy.

2019-07-01 12:29 UTC, mras2303 commented
Nie zmieniaj żadnej wartości w lastly.
Jeśli w polu lastly znajduje się today lub yesterday, ma to traktować jako dzień wczorajszy / dzisiejszy. Jeśli jeden z warunków jest spełniony, pole online ma zmienić na true
a) pole zawiera `today`
b) pole zawiera `yesterday`
c) data w lastly jest w odpowiednim zakresie (tutaj max 30 dni przed dniem dzisiejszym)

2019-07-02 11:07 UTC, mras2303 commented on users.js
> +      user.lastly.includes("today at") || user.lastly.includes("yesterday at")
Akceptuję, chociaż do poczytania o regexie :)

2019-07-02 11:18 UTC, hendrysiak commented
Jeśli chcesz zobaczy, to przerobię to na wyrażenie regularne :)

2019-07-02 11:47 UTC, mras2303 commented
> Jeśli chcesz zobaczy, to przerobię to na wyrażenie regularne :)

Pull Request będzie otwarty, zadanie zaakceptowane, ale jeśli zrobisz to ocenię :)

2019-07-05 21:39 UTC, closed without merging