js - very easy (solved)
fed-team/js-test pull request #4
Opened 2019-07-14 16:03 UTC by Regyu

2019-07-14 16:10 UTC, mras2303 commented on very easy/28.js
> +	return numArgs.arguments.length;
arguments jest wbudowane w funkcje, więc możesz pominąć nazwę funkcji

2019-07-14 16:11 UTC, mras2303 commented on very easy/29.js
> +	return Math.pow(num, exp);
Ok, ale w JS został dodany operator do potęg

2**4 = 16

2019-07-14 16:11 UTC, hayuna approved these changes

2019-07-20 17:22 UTC, mras2303 commented on easy/12.js
> +    for (let i = 0; i < perc.length; i++) {
You can use ES6 function `map` to make it better :)

2019-07-20 17:24 UTC, mras2303 commented on easy/13.js
> +    return word.includes(prefix.substring(0, prefix.length - 1));
test(isPrefix('unboxing', 'box-'), ???)

what should this example return? I think false, because this is not prefix. The same for suffix

2019-07-20 17:26 UTC, mras2303 commented on easy/15.js
> +    for (let i = 0; i < arr.length; i++) {
You can use ES6 functions to do that. At least forEach, better with every

2019-07-20 17:27 UTC, mras2303 commented on easy/16.js
> +    let numberOfChars = 0;
To read: indexOf, lastIndexOf

2019-07-20 17:38 UTC, mras2303 commented on easy/18.js
> +        } else if (str[i] === str[i].toLowerCase()) {
Is this else if require?

2019-07-20 17:38 UTC, mras2303 commented on easy/18.js
> +    for (let i = 0; i < str.length; i++) {
You can use forEach for this

2019-07-20 17:40 UTC, mras2303 commented on easy/22.js
> +    for (let i = 0; i < str.length; i++) {
You can use ES6 function `forEach` or better `reduce`

2019-07-20 17:41 UTC, mras2303 commented on easy/24.js
> +    for (let i = 0; i < arr.length; i++) {
You can use `find` for this

2019-07-20 17:44 UTC, mras2303 commented on easy/25.js
> +function isZipCode(zipcode) {
I see that you are using regex, so you could use regex method - `test` ;)

2019-07-20 17:46 UTC, mras2303 commented on easy/3.js
> +    return arrMaxMin;
this variable is not need

2019-07-20 17:48 UTC, mras2303 commented on easy/4.js
> +    else if(step>1){
Figure out that these if's fulfill the same condition for step = 1

2019-07-20 17:54 UTC, mras2303 commented on easy/5.js
> +    return arr.filter(function (el) {return el!=null});
You can use `arrow function` and skip return and curly brackets

2019-07-20 18:06 UTC, hayuna requested changes
Knowledge about ES6 is required for further checking

2019-07-27 05:56 UTC, mras2303 commented on easy/11.js
> +    const uniqueArr = new Set(arr);
You can remove uniqueArr and write it in one line

2019-07-27 05:57 UTC, mras2303 commented on easy/14.js
> +    const alphabet= `abcdefghijklmnopqrstuvwxyz`;
You can use regex instead of declaring variable with every letters

2019-07-27 05:57 UTC, mras2303 commented on easy/17.js
> +    const vowels="aeiou";
You can use lastIndexOf and indexOf

2019-07-27 05:58 UTC, mras2303 commented on easy/18.js
> +    let convertedStr=[];
You can use findIndex

2019-07-27 05:59 UTC, mras2303 commented on easy/15.js
> +    let check = 0;
You can use every

2019-07-27 05:59 UTC, mras2303 commented on easy/16.js
> +    let numberOfChars = 0;
You can use lastIndexOf and indexOf

2019-07-27 06:00 UTC, mras2303 commented on easy/19.js
> +    let dateString = date.toDateString();
Why are you declare new variable?

2019-07-27 06:00 UTC, mras2303 commented on easy/2.js
> +    if (num == 1) {
You can use ternary operator

2019-07-27 06:01 UTC, mras2303 commented on easy/20.js
> +    let sum=0;
You can use filter

2019-07-27 06:02 UTC, mras2303 commented on easy/22.js
> +    let charNumber = 0;
You can use reduce

2019-07-27 06:03 UTC, mras2303 commented on easy/23.js
> +    let sum=1;
You can use reduce for this

2019-07-27 06:03 UTC, mras2303 commented on easy/24.js
> +    for (let i = 0; i < arr.length; i++) {
You can use map

2019-07-27 06:03 UTC, mras2303 commented on easy/25.js
> +function isZipCode(zipcode) {
You can use better regex to validate it

2019-07-27 06:04 UTC, mras2303 commented on easy/26.js
> +    let numReversed=num.toString().split("").reverse().join("");
You can remove numReversed and write it in one line

2019-07-27 06:04 UTC, mras2303 commented on easy/28.js
> +    let average=0;
You can use reduce to sum elements

2019-07-27 06:04 UTC, mras2303 commented on easy/29.js
> +    let strArray = [];
You can use map

2019-07-27 06:05 UTC, mras2303 commented on easy/3.js
> +    let arrMaxMin=[Math.min.apply(null, arr),Math.max.apply(null, arr)];
You can remove arrMaxMin and write it in one line

2019-07-27 06:05 UTC, mras2303 commented on easy/4.js
> +    if(step==1)
First if is unnecessary

2019-07-27 06:05 UTC, mras2303 commented on easy/5.js
> +    return arr.filter(function (el) {return el!=null});
Please use arrow function and skip curly brackets and return

2019-07-27 06:06 UTC, mras2303 commented on easy/6.js
> +    let arr = [];
You can use map

2019-07-27 06:06 UTC, mras2303 commented on easy/8.js
> +    let firstLetters=[];
You can use map

2019-07-27 06:06 UTC, mras2303 commented on easy/9.js
> +    let hashPlusArray=[0,0];
You can use regex

2019-07-27 06:07 UTC, mras2303 commented on very easy/13.js
> +	return lastName + ", " + firstName}
You can use template literal

2019-07-27 06:07 UTC, mras2303 commented on very easy/19.js
> +    let sum=0;
You can use reduce

2019-07-27 06:07 UTC, mras2303 commented on very easy/21.js
> +    if (num % 2 == 0) {
You can use ternary operator instead of if

2019-07-27 06:08 UTC, mras2303 commented on very easy/25.js
> +	return c.charCodeAt(0);
0 is default value in this method. You can skip it

2019-07-27 06:08 UTC, mras2303 commented on very easy/27.js
> +	return total/(people*each)>=1;
Why in the conditional >=1 not >0 ? Are you sure that dividing by zero could be good solution?

2019-07-27 06:08 UTC, mras2303 commented on very easy/28.js
> +	return numArgs.arguments.length;
arguments is build-in value. You can skip numArgs

2019-07-27 06:08 UTC, mras2303 commented on very easy/29.js
> +	return Math.pow(num, exp);
Good, but in ES7 has added operator of exponent - **

2019-07-27 06:08 UTC, mras2303 commented on very easy/30.js
> +    return arr.indexOf(str);
You can use findIndex

2019-07-29 19:47 UTC, mras2303 commented on easy/16.js
> +    } else return undefined;
You can skip else. When `if` would be fulfilled then return array and next part of code won't be executed. You can just type `return` after curly brackets in `if`

2019-07-29 19:57 UTC, mras2303 commented on easy/25.js
> +function isZipCode(zipcode) {
Improve your pattern to validate zipcode XX-XXX

2019-07-29 19:57 UTC, hayuna requested changes
Could you check these tasks?

easy 13
easy 16
easy 25

2019-07-29 21:21 UTC, mras2303 commented on easy/13.js
> +    return word.includes(prefix.substring(0, prefix.length - 1));
This is not working for isPrefix('arachnophobia', 'no-')
expected false, Actual true

2019-08-05 14:46 UTC, mras2303 commented
- 13 isPrefix('arachnophobia', 'no-'). //true   is this correct statement?
- 16 You can skip else. When `if` would be fulfilled then return array and next part of code won't be executed. You can just type `return` after curly brackets in `if`
- 25 Improve your pattern to validate zipcode XX-XXX

Result: 93.33%

2019-10-10 10:52 UTC, closed without merging